### ISSUE TITLE
Esse grupo é só para programador?

### ISSUE THREAD

**Issue by leocavalcante** [desenvolvimento-web/agora#1]
Assunto: https://www.facebook.com/groups/desenvolvimentoweb/permalink/3028495293875556/

---

Recebi muito report com relação à esse post, mas sendo mais objetivo e imparcial possível com minhas atribuições de moderador, ele não infringe nenhuma regra diretamente.

Ou infringe? O que vocês acham?

(Se tiver muito like/thumbs-up aqui eu converso com o @yuricamara pra gente deletar)

**Comment by yuricamara** [comment]
Olá @leocavalcante ,

Não infringe não! E o grupo não é só para programador. É para todos. Basta seguirem as regras.

**Comment by leocavalcante** [comment]
Oi @yuricamara 
O problema é que ele tá usando só pra divulgar o Builderall, deve fazer parte do programa de afiliação: https://affiliates.builderall.com/ O "Esse grupo é só para programador?" foi só bait pra ele falar que faz site sem programar e "pergunte-me como".

**Comment by yuricamara** [comment]
"Esse grupo é só para programador?" Achei que fosse uma dúvida sua!

Então apaga!
